### ISSUE TITLE
Fitting loops (after completion?)

### ISSUE THREAD

**Issue by AntonLydike** [MDeiml/look#1]
The fitting improves for a while (seemingly until "completion" at 32 polynomials), and then jumps back to a state with only 10-12 curves. Is this expected behavior?

**Comment by MDeiml** [comment]
Yes it's intended behavior. It selects the 16 curves that best fit the image. Do you think it would be better without that?

**Comment by AntonLydike** [comment]
I thought the previous behavior of selecting a new image and starting over was actually super nice as a sort-of screensaver

**Comment by MDeiml** [comment]
Also try pressing "o" now ;)
